# HINT: daocloud update its vllm version to 0.10.1.dev1+gbcc0a3cbe
FROM docker.m.daocloud.io/vllm/vllm-openai:v0.10.0

COPY vllm/model_executor/models/megatron_bert.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/megatron_bert.py

COPY vllm/model_executor/models/registry.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
