# use public vllm-metax image
FROM pub-registry1.metax-tech.com/ai-opentest/master/maca/vllm-metax:0.15.0-maca.ai20260227-177-torch2.8-py312-ubuntu22.04-amd64

# set vllm path
ARG VLLM_PATH="/opt/conda/lib/python3.12/site-packages/vllm"
# set vllm-metax path
ARG VLLM_METAX_PATH="/opt/conda/lib/python3.12/site-packages/vllm-metax"

ARG PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"

ARG PIP_INSTALL_COMMAND="/opt/conda/bin/pip install"
# install soxr librosa soundfile
RUN ${PIP_INSTALL_COMMAND} soxr librosa soundfile -i ${PIP_INDEX_URL}

ENTRYPOINT ["vllm", "serve"]