FROM cr.metax-tech.com/public-ai-release/maca/vllm-metax:0.14.0-maca.ai3.5.3.102-torch2.8-py312-ubuntu22.04-amd64
# FROM cr.metax-tech.com/public-ai-release/maca/vllm-metax:0.14.0-maca.ai3.5.3.102-torch2.8-py312-kylinv11-amd64

ARG VLLM_PATH="/opt/conda/lib/python3.12/site-packages/vllm"

# add qwen3.5 transformers configs
COPY vllm/transformers_utils/configs/qwen3_5.py ${VLLM_PATH}/transformers_utils/configs/qwen3_5.py
COPY vllm/transformers_utils/configs/qwen3_5_moe.py ${VLLM_PATH}/transformers_utils/configs/qwen3_5_moe.py
COPY vllm/transformers_utils/configs/__init__.py ${VLLM_PATH}/transformers_utils/configs/__init__.py
COPY vllm/transformers_utils/config.py ${VLLM_PATH}/transformers_utils/config.py


# add qwen3.5 transformers models, we need to enhance qwen3_next model to support qwen3.5
COPY vllm/model_executor/models/qwen3_next.py ${VLLM_PATH}/model_executor/models/qwen3_next.py
COPY vllm/model_executor/models/qwen3_5.py ${VLLM_PATH}/model_executor/models/qwen3_5.py
COPY vllm/model_executor/models/qwen3_5_mtp.py ${VLLM_PATH}/model_executor/models/qwen3_5_mtp.py
COPY vllm/model_executor/models/registry.py ${VLLM_PATH}/model_executor/models/registry.py

# enhance qwen3.5 transformers layers
COPY vllm/model_executor/layers/linear.py ${VLLM_PATH}/model_executor/layers/linear.py
COPY vllm/model_executor/layers/mamba/abstract.py ${VLLM_PATH}/model_executor/layers/mamba/abstract.py

ENTRYPOINT ["vllm", "serve"]