# support the newer version of vllm/vllm-openai:v0.10.0
FROM docker.m.daocloud.io/vllm/vllm-openai:v0.10.0

# HINT: the newer version of vllm==0.10.1.dev1 is based on transformers==4.54.1
# add transformers parrot audio support
COPY dist/transformers-4.54.1.tar.gz /tmp/transformers-4.54.1.tar.gz
RUN pip uninstall transformers -y && pip install /tmp/transformers-4.54.1.tar.gz --no-deps && rm -rf /tmp/transformers-4.54.1.tar.gz

# add parrot commons support
COPY dist/parrot_commons-0.1.0.tar.gz /tmp/parrot_commons-0.1.0.tar.gz
RUN pip install /tmp/parrot_commons-0.1.0.tar.gz --no-deps && rm -rf /tmp/parrot_commons-0.1.0.tar.gz

# add vllm kubernetes plugin support
COPY dist/vllm_kubernetes_plugin-0.1.0.tar.gz /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz
RUN pip install /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz --no-deps && rm -rf /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz

# HINT: torchaudio issue was fixed in new verison of vllm/vllm-openai:v0.10.0

# add vllm parrot audio support
COPY vllm/model_executor/model_loader/mixed_precision_utils.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/mixed_precision_utils.py
COPY vllm/model_executor/model_loader/base_loader.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/base_loader.py

COPY vllm/inputs/registry.py /usr/local/lib/python3.12/dist-packages/vllm/inputs/registry.py

COPY vllm/model_executor/models/parrot_audio.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/parrot_audio.py
COPY vllm/model_executor/models/parrot2_audio.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/parrot2_audio.py
COPY vllm/model_executor/models/parrot2_audio_moe.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/parrot2_audio_moe.py

COPY vllm/model_executor/models/registry.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py


ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
