FROM docker.m.daocloud.io/vllm/vllm-openai:v0.17.0

RUN pip install soxr librosa soundfile -i https://pypi.tuna.tsinghua.edu.cn/simple

ARG VLLM_PATH="/usr/local/lib/python3.12/dist-packages/vllm"

COPY vllm/model_executor/models/qwen3_asr.py ${VLLM_PATH}/model_executor/models/qwen3_asr.py
COPY vllm/model_executor/models/qwen3_asr_realtime.py ${VLLM_PATH}/model_executor/models/qwen3_asr_realtime.py

COPY vllm/v1/engine/core_client.py ${VLLM_PATH}/v1/engine/core_client.py
COPY vllm/v1/engine/output_processor.py ${VLLM_PATH}/v1/engine/output_processor.py
COPY vllm/entrypoints/openai/realtime/connection.py ${VLLM_PATH}/entrypoints/openai/realtime/connection.py
COPY vllm/v1/core/sched/async_scheduler.py ${VLLM_PATH}/v1/core/sched/async_scheduler.py

COPY vllm/entrypoints/openai/speech_to_text/speech_to_text.py ${VLLM_PATH}/entrypoints/openai/speech_to_text/speech_to_text.py

ENTRYPOINT ["vllm", "serve"]
