FROM docker.m.daocloud.io/vllm/vllm-openai:v0.8.5.post1

COPY vllm/model_executor/models/megatron_bert.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/megatron_bert.py

COPY vllm/model_executor/models/registry.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]