FROM docker.m.daocloud.io/vllm/vllm-openai:v0.9.2

# add transformers funasr nano support
COPY dist/transformers-4.57.3.tar.gz /tmp/transformers-4.57.3.tar.gz
RUN pip uninstall transformers -y && pip install /tmp/transformers-4.57.3.tar.gz --no-deps && rm -rf /tmp/transformers-4.57.3.tar.gz

# `torchaudio` already installed in base image
RUN pip install librosa==0.11.0

# add vllm mixed precision model loader
COPY vllm/model_executor/model_loader/mixed_precision_loader.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/mixed_precision_loader.py
COPY vllm/model_executor/model_loader/__init__.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py
COPY vllm/config.py /usr/local/lib/python3.12/dist-packages/vllm/config.py
COPY vllm/inputs/registry.py /usr/local/lib/python3.12/dist-packages/vllm/inputs/registry.py

# add vllm funasr nano support
COPY vllm/model_executor/models/funasr_nano.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/funasr_nano.py
COPY vllm/model_executor/models/registry.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
