# v0.9.2
FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.2-py3.10

# # v0.9.2-20250916-rc2-ds3.2
# FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas104381-0915-das1.6-py3.10-20250916-rc2-ds3.2

# # v0.9.2-20250916-rc2
# FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas104381-0915-das1.6-py3.10-20250916-rc2

# # v0.9.2-20250913-rc1
# FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas101839-0811-das1.6-py3.10-20250913-rc1

# # v0.9.2-20250908-rc1
# FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas101839-0811-das1.6-py3.10-20250908-rc1

# # v0.9.2-20250812-beta
# FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas101839-0811-das1.6-py3.10-20250812-beta

# # v0.9.2-20250810-alpha
# FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas101839-das1.6-py3.10-20250810-alpha


# add vllm tei plugin support
# COPY dist/vllm_tei_plugin-0.9.2.tar.gz /tmp/vllm_tei_plugin-0.9.2.tar.gz
# RUN pip install /tmp/vllm_tei_plugin-0.9.2.tar.gz --no-deps && rm -rf /tmp/vllm_tei_plugin-0.9.2.tar.gz

# add vllm kubernetes plugin support
# COPY dist/vllm_kubernetes_plugin-0.1.0.tar.gz /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz
# RUN pip install /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz --no-deps && rm -rf /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz

# add transformers parrot audio support
COPY dist/transformers-4.57.1.tar.gz /tmp/transformers-4.57.1.tar.gz
RUN pip uninstall transformers -y && pip install /tmp/transformers-4.57.1.tar.gz --no-deps && rm -rf /tmp/transformers-4.57.1.tar.gz

# `torchaudio` already installed in base image
RUN pip install librosa==0.11.0

ARG PYTHON_VERSION=3.10
ARG VLLM_INSTALL_DIR=/usr/local/lib/python${PYTHON_VERSION}/dist-packages/vllm

# add vllm mixed precision model loader
COPY vllm/model_executor/model_loader/mixed_precision_loader.py ${VLLM_INSTALL_DIR}/model_executor/model_loader/mixed_precision_loader.py
COPY vllm/model_executor/model_loader/__init__.py ${VLLM_INSTALL_DIR}/model_executor/model_loader/__init__.py
# vllm hygon's config.py is different from the original vllm, so we need to patch it
COPY docker/vllm_patch/config.py ${VLLM_INSTALL_DIR}/config.py
COPY vllm/inputs/registry.py ${VLLM_INSTALL_DIR}/inputs/registry.py

# add vllm parrot audio support
COPY dist/parrot_commons-0.1.0.tar.gz /tmp/parrot_commons-0.1.0.tar.gz
RUN pip install /tmp/parrot_commons-0.1.0.tar.gz --no-deps && rm -rf /tmp/parrot_commons-0.1.0.tar.gz

COPY vllm/model_executor/models/parrot_audio.py ${VLLM_INSTALL_DIR}/model_executor/models/parrot_audio.py
COPY vllm/model_executor/models/parrot2_audio.py ${VLLM_INSTALL_DIR}/model_executor/models/parrot2_audio.py
COPY vllm/model_executor/models/parrot2_audio_moe.py ${VLLM_INSTALL_DIR}/model_executor/models/parrot2_audio_moe.py
COPY vllm/model_executor/models/registry.py ${VLLM_INSTALL_DIR}/model_executor/models/registry.py

# TODO: still some problems with the parrot audio support, need to fix it later
ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
