FROM cr.metax-tech.com/public-ai-release/maca/vllm-metax:0.13.0-maca.ai3.3.0.303-torch2.8-py312-ubuntu22.04-amd64
# FROM cr.metax-tech.com/public-ai-release/maca/vllm-metax:0.13.0-maca.ai3.3.0.303-torch2.8-py312-kylinv11-amd64

ARG VLLM_PATH="/opt/conda/lib/python3.12/site-packages/vllm"

# add tei serving handler
COPY vllm/entrypoints/tei ${VLLM_PATH}/entrypoints/tei

# add tei serving router
COPY vllm/entrypoints/pooling/embed/api_router.py ${VLLM_PATH}/entrypoints/pooling/embed/api_router.py
COPY vllm/entrypoints/pooling/score/api_router.py ${VLLM_PATH}/entrypoints/pooling/score/api_router.py
COPY vllm/entrypoints/openai/api_server.py ${VLLM_PATH}/entrypoints/openai/api_server.py

ENTRYPOINT ["vllm", "serve"]